// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzgvdzzaaykhqqtombgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6Z3ZkenphYXlraHFxdG9tYmd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjY2NzAsImV4cCI6MjA2OTU0MjY3MH0.KPseS5GuUVZ0sAsNQLWU7qu02nqdeu960TEV5g2PaPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});